import {ClassType} from 'app/metatypes'
import {
  ColorsBtn,
  GenericBtn,
} from '../buttons'

interface Item {
  name: string;
  component?: ClassType<GenericBtn>;
}

export const items: Array<Item> = [
  {name: '8-bit'},
  {name: 'Anathema'},
  {name: 'Android'},
  {name: 'Angular'},
  {name: 'bash.org'},
  {name: 'Belarus'},
  {name: 'Bicycle'},
  {name: 'Billiard'},
  {name: 'BitBucket'},
  {name: 'Board games'},
  {name: 'Cats'},
  {name: 'Chrome'},
  {name: 'Colors', component: ColorsBtn},
  {name: 'Curriculum vitae'},
  {name: 'Debian'},
  {name: 'Deep Purple'},
  {name: 'Design'},
  {name: 'Drums'},
  {name: 'Email'},
  {name: 'EN'},
  {name: 'Epam'},
  {name: 'Facebook'},
  {name: 'Family'},
  {name: 'Family Guy'},
  {name: 'Firefox'},
  {name: 'foobar2000'},
  {name: 'GitHub'},
  {name: 'God Is An Astronaut'},
  {name: 'Google'},
  {name: 'Grodno'},
  {name: 'Habr'},
  {name: 'Half Life'},
  {name: 'Heroes of Might and Magic 3'},
  {name: 'Hive'},
  {name: 'iOS'},
  {name: 'Java'},
  {name: 'JavaScript'},
  {name: 'Joy in Time'},
  {name: 'Krako\u0301w'},
  {name: 'Langaroo'},
  {name: 'Last.fm'},
  {name: 'Lego'},
  {name: 'LinkedIn'},
  {name: 'Lunatic Soul'},
  {name: 'Minsk'},
  {name: 'Music'},
  {name: 'NES'},
  {name: 'Night'},
  {name: 'Novopolotsk'},
  {name: 'Opeth'},
  {name: 'Paiste'},
  {name: 'Phil Tsarik'},
  {name: 'phts'},
  {name: 'Pilip Tsaryk'},
  {name: 'Pink Floyd'},
  {name: 'Pixel Dungeon'},
  {name: 'Playing cards'},
  {name: 'Poland'},
  {name: 'PSU'},
  {name: 'React'},
  {name: 'Ritchie Blackmore'},
  {name: 'Riverside'},
  {name: 'RU'},
  {name: 'Ruby'},
  {name: 'SaM Solutions'},
  {name: 'S\u030Ckoda'},
  {name: 'Skype'},
  {name: 'Sleep'},
  {name: 'Software Developer'},
  {name: 'Sound'},
  {name: 'Space Resonance'},
  {name: 'Space'},
  {name: 'Stack Overflow'},
  {name: 'Sublime Text'},
  {name: 'Syberia'},
  {name: 'Tel number'},
  {name: 'The Gathering'},
  {name: 'The Netherlands'},
  {name: 'Travel'},
  {name: 'Typescript'},
  {name: 'Uber'},
  {name: 'Ultramarined'},
  {name: 'Vater 5A Los Angeles'},
  {name: 'Video games'},
  {name: 'Vk'},
  {name: 'Waterfox'},
  {name: 'Windows'},
  {name: 'ZX Spectrum'},
  {name: '© Phil Tsarik, 2017'},
]
