version: 2
jobs:
  test:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm test

  deploy-dev:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run build:prod:relative
      - add_ssh_keys:
          fingerprints:
            - 'ef:f5:a9:bb:63:8d:9e:1d:ce:ab:1b:12:8d:a3:db:22'
      - deploy:
          command: npm run deploy:dev

  deploy-prod:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm ci
      - run: npm run build:prod
      - add_ssh_keys:
          fingerprints:
            - 'ef:f5:a9:bb:63:8d:9e:1d:ce:ab:1b:12:8d:a3:db:22'
      - deploy:
          command: npm run deploy:prod

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy-dev:
          requires:
            - test
          filters:
            branches:
              only: /dev-.*/
      - deploy-prod:
          requires:
            - test
          filters:
            branches:
              only: master
