name: Test and deploy (dev)

on:
  push:
    branches:
      - dev-*

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
          cache: 'npm'
      - uses: actions/checkout@v3
      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - if: ${{ steps.node-modules-cache.outputs.cache-hit != 'true' }}
        name: Fresh install
        run: npm ci

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - uses: actions/checkout@v3
      - name: Load node_modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Lint
        run: npm run lint

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - uses: actions/checkout@v3
      - name: Load node_modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Test
        run: npm test

  deploy:
    needs: [install, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - uses: actions/checkout@v3
      - name: Load node_modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Build
        run: npm run build:prod:relative
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          clean: true
          commit-message: 'chore: publish branch \"${{ github.ref_name }}\"'
          folder: dist
          git-config-email: phil@tsaryk.com
          git-config-name: CI
          target-folder: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
